### ISSUE TITLE
Supporting files

### ISSUE THREAD

**Issue by mbnoimi** [KODeKarnage/script.lazytv#13]
I suggest to add Files support along side to TV Shows and Movies because there are many multimedia sources not scrapped by known scrappers (ex. IMDB) specially for non-English materials.

**Comment by KODeKarnage** [comment]
Not feasible, unfortunately. LazyTV uses the library to determine the next episode to watch, it doesn't do any of its own parsing of filenames to determine episode order. It's a pretty big task to replicate the name parsing that is already done by the library.
