### ISSUE TITLE
Smart playlist is in random order

### ISSUE THREAD

**Issue by martinl88** [KODeKarnage/script.lazytv#25]
When I look at the list from the LazyTV program add-on it sorts the shows by last watched (as expected). When I open the smart playlist LazyTV creates it is in random order (random as in the order is totally messed up and changes every time I open the playlist).

**Comment by KODeKarnage** [comment]
What exactly do you mean by "smart playlist"? Do you mean the random player? Because that is the intended way it works. It plays random TV shows.

**Comment by martinl88** [comment]
Well, KODI wiki says:
> 2.4 Create and maintain smart playlist
> Selecting this option will instruct LazyTV to create and maintain a smart playlist with all of your next available episodes. LazyTV will keep the smart playlist synchronised with database and watched status updates. (Requires restart of LazyTV service.) This playlist can then be used on its own or in conjunction with other addons such as PseudoTV. The LazyTV smart playlist can also be used as a criteria in other smart playlists; simply include a rule in those playlists that says "Playlist IS LazyTV". 

It doesn't say anything about being random. I was hoping that it outputs the shows in the same order as the "app" itself so I can use it to fill the skin's shelf.

**Comment by martinl88** [comment]
They seem to be after the same thing:

- https://forum.kodi.tv/showthread.php?tid=170975&pid=2715082#pid2715082
- https://forum.kodi.tv/showthread.php?tid=170975&pid=2740152#pid2740152

I basically want to achieve the same thing - https://forum.kodi.tv/showthread.php?tid=331334&pid=2833170#pid2833170

That's the way the original Quartz skin worked. Shelf for TV Shows always showed the next episode for a specific show. Shows were ordered by "last watched" (so for example if I'd be binge-watching Family Guy, the next episode would always be first in line)

**Comment by KODeKarnage** [comment]
Ah, that is an actual playlist file. 
Solution: You can simply create a new smart playlist in Kodi, set the rule to be "Playlist is LazyTV" (as described on the wiki) and then set the Order to "Last Watched". LazyTV will keep the underlying playlist up-to-date, which will in turn keep your new playlist up-to-date, but in the order you were looking for.

**Comment by KODeKarnage** [comment]
P.S. Make sure the playlist type is set to Episodes and that the Order is descending.

**Comment by martinl88** [comment]
That idea sounded great... until I tried it. Yes, LazyTV playlist has correct episodes (although in random) and I can pull the contents to another smart playlist.. but I can't sort it using the "last played" because those are unplayed episodes and they don't have "last played" set.
Correct "last played" timestamp is with TV Shows... but I can't use it with "Episodes" playlist. 
So basically I need some kind of a _join_ query.

**Comment by martinl88** [comment]
Ideally it could be solved with a static playlist that has the same contents as the app.

It seems there are others in the need of that kind of functionality as well - https://forum.kodi.tv/showthread.php?tid=343864

**Comment by KODeKarnage** [comment]
Ah, the LastPlayed stat for episodes comes through only for partially watched episodes. The only fix for that is to have the file record the episodes in order, and not rely on Kodi to do it. If you are on Matrix there is an update to 3.0.1 awaiting approval to be added to the repo. This will add an option in Settings to match the smartplaylist order to the order shown in the List section. The default behaviour will continue to be random, though, as some people might be using that already.

**Comment by martinl88** [comment]
Thanks. I'll take a look!

**Comment by coreyp93** [comment]
As matrix is still in alpha and leia is still the stable version, is there any way you can push this change to leia? I would be really grateful especially until matrix is suitable. It's the piece missing in my setup and I like using lazytv😁
